*** Variables ***
${SIGNUP_EMAIL}                 xpath=//android.widget.EditText[@resource-id='ap_email_login']
${SIGNUP_CONTINUE_BUTTON}       xpath=//android.widget.Button[@resource-id='continue']
${SIGNUP_PASSWORD}              xpath=//android.widget.EditText[@resource-id='ap_password']
${SIGNUP_BUTTON}                xpath=//android.widget.Button[@resource-id='signInSubmit']
${SIGNUP_NOT_NOW}               xpath=//android.view.View[@content-desc="Not now"]
