*** Variables ***
${SEARCH_BAR_HINT_VIEW}                 com.amazon.mShop.android.shopping:id/chrome_search_hint_view
${SEARCH_BAR_INPUT}                     com.amazon.mShop.android.shopping:id/rs_search_src_text
${SEARCH_BAR_SEARCH_ICON}               com.amazon.mShop.android.shopping:id/chrome_action_bar_search_icon
${SEARCH_ELEMENT_WITH_SEARCH_OFFER}     com.amazon.mShop.android.shopping:id/iss_search_dropdown_item_suggestions